### ISSUE TITLE
model

### ISSUE THREAD

**Issue by Le312** [zhangjun001/FGNet#2]
Hi, I am now reproducing your paper, but an error is reported at line 318 in reference--checkpoint 1000: KeyError: 'conv1.lin.weight', is this a model mismatch problem?

**Comment by HowardHuazy** [comment]
Hello Le,

I believe it's because of a pytroch-geometric version discrepancy. Back then, we used an older version of pytorch-geomtric library, and you installed the latest one.

However, I have found a solution for you, should be a simple fix:

https://github.com/pyg-team/pytorch_geometric/discussions/3171

Thank you
